name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.6
  - pytorch==1.4.0
  # utils
  - torchvision==0.5.0
  - opencv==4.2.0
  - matplotlib==3.2.1
  - ipython==7.8.0
  - jupyter==1.0.0
  # test
  - pytest==5.1.2
  - pytest-cov==2.7.1
  - flake8==3.7.8
  - autopep8==1.4.4
  - mypy==0.720
  - mypy_extensions==0.4.1
  # docs
  - sphinx==2.1.2
  - sphinx-gallery==0.4.0
  - sphinxcontrib-bibtex==0.4.2
  - nbsphinx==0.4.2
  - nbconvert==5.5.0
  - notebook==6.0.1
  - pip:
    - git+https://github.com/kornia/kornia_sphinx_theme.git
